### ISSUE TITLE
demo application start up not working

### ISSUE THREAD

**Issue by bharatesh** [mmasiukevich/service-bus#144]
Hi There, 

I am trying to setup demo application. Docker compose is not able to start following container
`service-bus-uber-consumer` 
When I looked into docker-compose.yml file the following line
https://github.com/php-service-bus/demo/blob/d53b8cdb151fb7a7da29fa35200bdae91994697d/docker-compose.yaml#L45
But `/tools/boot` does not exist.

**Comment by mmasiukevich** [comment]
Greetings

The demo application has not been updated for a long time, unfortunately. Over the weekend, I’ll deal with this issue.

**Comment by mmasiukevich** [comment]
done)
